# Generated by Django 4.2.15 on 2025-01-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mesin', models.CharField(max_length=200, unique=True)),
                ('tipe', models.CharField(blank=True, max_length=100, null=True)),
                ('tahun_pembuatan', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mesin',
                'verbose_name_plural': 'Mesin',
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('link_khusus', models.CharField(max_length=255, unique=True)),
                ('jenis_proses', models.CharField(choices=[('mixing', 'Mixing'), ('filling', 'Filling'), ('packaging', 'Packaging'), ('quality_control', 'Quality Control')], default='mixing', max_length=50)),
                ('mesin', models.ManyToManyField(related_name='ruangan', to='produksi_monitoring.mesin')),
            ],
            options={
                'verbose_name': 'Ruangan',
                'verbose_name_plural': 'Ruangan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_batch', models.CharField(max_length=100, unique=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('satuan', models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces'), ('liter', 'Liter'), ('pack', 'Pack')], default='kg', max_length=10)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Proses'), ('sedang_diproses', 'Sedang Diproses'), ('selesai', 'Selesai')], default='menunggu', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('mesin', models.ManyToManyField(related_name='produk', to='produksi_monitoring.mesin')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.ruangan')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
            },
        ),
    ]
