# Generated by Django 4.2.15 on 2025-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name': 'Proses Produksi', 'verbose_name_plural': 'Proses Produksi'},
        ),
        migrations.RemoveField(
            model_name='mesin',
            name='tahun_pembuatan',
        ),
        migrations.RemoveField(
            model_name='mesin',
            name='tipe',
        ),
        migrations.AddField(
            model_name='mesin',
            name='kode_mesin',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ruangan',
            name='kode_ruangan',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
