# Generated by Django 4.2.15 on 2025-01-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0002_alter_produk_options_remove_mesin_tahun_pembuatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsesProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_batch', models.CharField(max_length=100, unique=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('satuan', models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces'), ('liter', 'Liter'), ('pack', 'Pack')], default='kg', max_length=10)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Proses'), ('sedang_diproses', 'Sedang Diproses'), ('selesai', 'Selesai')], default='menunggu', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('waktu_mulai_produksi', models.DateTimeField(blank=True, null=True)),
                ('mesin', models.ManyToManyField(related_name='produk', to='produksi_monitoring.mesin')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.ruangan')),
            ],
            options={
                'verbose_name': 'Proses Produksi',
                'verbose_name_plural': 'Proses Produksi',
            },
        ),
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
