# Generated by Django 4.2.15 on 2025-01-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0003_prosesproduksi_delete_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang_diproses', 'Sedang Diproses'), ('Selesai', 'Selesai')], default='menunggu', max_length=20),
        ),
    ]
