# Generated by Django 4.2.15 on 2025-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0004_alter_prosesproduksi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosesproduksi',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
