# Generated by Django 4.2.15 on 2025-01-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0005_prosesproduksi_waktu_selesai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang_diproses', 'Sedang Diproses')], default='menunggu', max_length=20),
        ),
    ]
