# Generated by Django 4.2.15 on 2025-02-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0007_itemdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescription',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
