# Generated by Django 4.2.15 on 2025-02-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0008_alter_itemdescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.itemdescription'),
        ),
    ]
