# Generated by Django 4.2.15 on 2025-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0009_alter_prosesproduksi_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='jenis_proses',
            field=models.CharField(choices=[('weighing', 'Weighing'), ('processing', 'Processing'), ('mixing', 'Mixing'), ('filling', 'Filling'), ('packaging', 'Packaging'), ('labelling', 'Labelling'), ('quality_control', 'Quality Control')], default='mixing', max_length=50),
        ),
    ]
