# Generated by Django 4.2.15 on 2025-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0011_alter_prosesproduksi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='nomor_batch',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
