# Generated by Django 4.2.15 on 2025-02-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0012_alter_prosesproduksi_nomor_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='tahap_berikutnya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produksi_monitoring.ruangan'),
        ),
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang diproses', 'Sedang Diproses'), ('Selesai', 'Selesai')], default='Menunggu', max_length=20),
        ),
    ]
