# Generated by Django 4.2.15 on 2025-02-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0013_ruangan_tahap_berikutnya_alter_prosesproduksi_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prosesproduksi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ruangan',
            options={},
        ),
        migrations.RemoveField(
            model_name='prosesproduksi',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='prosesproduksi',
            name='mesin',
        ),
        migrations.RemoveField(
            model_name='prosesproduksi',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='prosesproduksi',
            name='waktu_mulai_produksi',
        ),
    ]
