# Generated by Django 4.2.15 on 2025-02-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0014_alter_mesin_options_alter_prosesproduksi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prosesproduksi',
            options={'verbose_name': 'Proses Produksi', 'verbose_name_plural': 'Proses Produksi'},
        ),
        migrations.AddField(
            model_name='prosesproduksi',
            name='waktu_mulai_produksi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prosesproduksi',
            name='nomor_batch',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
