# Generated by Django 4.2.15 on 2025-02-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0015_alter_prosesproduksi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesin',
            options={'verbose_name': 'Mesin', 'verbose_name_plural': 'Mesin'},
        ),
        migrations.AlterModelOptions(
            name='ruangan',
            options={'verbose_name': 'Ruangan', 'verbose_name_plural': 'Ruangan'},
        ),
    ]
