# Generated by Django 4.2.15 on 2025-02-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0017_alter_prosesproduksi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosesproduksi',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
