# Generated by Django 4.2.15 on 2025-02-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0018_prosesproduksi_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang Diproses', 'Sedang Diproses'), ('Siap Dipindahkan', 'Siap Dipindahkan'), ('Selesai', 'Selesai')], default='Menunggu', max_length=20),
        ),
    ]
