# Generated by Django 4.2.15 on 2025-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0019_alter_prosesproduksi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosesproduksi',
            name='operator',
        ),
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang diproses', 'Sedang Diproses'), ('Siap Dipindahkan', 'Siap Dipindahkan'), ('Selesai', 'Selesai')], default='Menunggu', max_length=20),
        ),
    ]
