# Generated by Django 4.2.15 on 2025-02-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0020_remove_prosesproduksi_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdescription',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
