# Generated by Django 4.2.15 on 2025-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0021_itemdescription_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='nomor_batch',
            field=models.CharField(blank=True, default='ISIKAN', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
