# Generated by Django 4.2.15 on 2025-02-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0022_alter_prosesproduksi_nomor_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang diproses', 'Sedang Diproses'), ('Siap Dipindahkan', 'Siap Dipindahkan'), ('Selesai', 'Selesai'), ('Selesai Produksi', 'Selesai Produksi')], default='Menunggu', max_length=20),
        ),
    ]
