# Generated by Django 4.2.15 on 2025-02-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0024_prosesproduksi_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='ruangan',
            field=models.ForeignKey(default='Ruang Penimbangan', on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.ruangan'),
        ),
    ]
