# Generated by Django 4.2.15 on 2025-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0026_alter_prosesproduksi_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('kategori', models.CharField(choices=[('Filling', 'Filling'), ('Proses', 'Proses')], max_length=50)),
            ],
        ),
    ]
