# Generated by Django 4.2.15 on 2025-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0027_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='kategori',
            field=models.CharField(choices=[('Penimbangan', 'Penimbangan'), ('Proses', 'Proses'), ('Filling', 'Filling'), ('Labelling', 'Labelling')], max_length=50),
        ),
    ]
