# Generated by Django 4.2.15 on 2025-02-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0028_alter_operator_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.operator'),
        ),
    ]
