# Generated by Django 4.2.15 on 2025-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0030_alter_prosesproduksi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosesproduksi',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
