# Generated by Django 4.2.15 on 2025-03-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0031_prosesproduksi_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_batch', models.CharField(max_length=20)),
                ('jumlah', models.PositiveIntegerField()),
                ('satuan', models.CharField(max_length=10)),
                ('waktu_mulai_produksi', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField()),
                ('nama_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.itemdescription')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.operator')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.ruangan')),
            ],
        ),
    ]
