# Generated by Django 4.2.15 on 2025-03-07 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0032_riwayatproduksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatLabelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_kemasan', models.PositiveIntegerField()),
                ('satuan_kemasan', models.CharField(choices=[('pcs', 'Pieces'), ('karton', 'Karton')], max_length=10)),
                ('waktu_input', models.DateTimeField(auto_now_add=True)),
                ('proses_produksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labelling_data', to='produksi_monitoring.prosesproduksi')),
            ],
        ),
    ]
