# Generated by Django 4.2.15 on 2025-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0033_riwayatlabelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosesproduksi',
            name='jumlah_kemasan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosesproduksi',
            name='satuan_kemasan',
            field=models.CharField(blank=True, choices=[('pcs', 'Pieces'), ('karton', 'Karton')], max_length=10, null=True),
        ),
    ]
