# Generated by Django 4.2.15 on 2025-03-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0034_prosesproduksi_jumlah_kemasan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatproduksi',
            name='nama_produk',
        ),
        migrations.RemoveField(
            model_name='riwayatproduksi',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='riwayatproduksi',
            name='ruangan',
        ),
        migrations.RemoveField(
            model_name='prosesproduksi',
            name='jumlah_kemasan',
        ),
        migrations.RemoveField(
            model_name='prosesproduksi',
            name='satuan_kemasan',
        ),
        migrations.DeleteModel(
            name='RiwayatLabelling',
        ),
        migrations.DeleteModel(
            name='RiwayatProduksi',
        ),
    ]
