# Generated by Django 4.2.15 on 2025-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0037_riwayatproduksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang diproses', 'Sedang Diproses'), ('Menunggu Verifikasi Admin', 'Menunggu Verifikasi Admin'), ('Selesai di Ruangan Ini', 'Selesai di Ruangan Ini'), ('Siap Dipindahkan', 'Siap Dipindahkan'), ('Selesai Produksi', 'Selesai Produksi')], default='Menunggu', max_length=30),
        ),
    ]
