# Generated by Django 4.2.15 on 2025-04-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0040_alter_prosesproduksi_satuan_kemasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosesproduksi',
            name='estimasi_jumlah_kemasan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
