# Generated by Django 4.2.15 on 2025-04-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0041_prosesproduksi_estimasi_jumlah_kemasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='nomor_batch',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
