# Generated by Django 4.2.15 on 2025-04-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0042_alter_prosesproduksi_nomor_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prosesproduksi',
            options={},
        ),
        migrations.AddField(
            model_name='prosesproduksi',
            name='hasil_akhir',
            field=models.CharField(blank=True, choices=[('', 'Belum Ditetapkan'), ('Release', 'Release'), ('Reject', 'Reject')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='prosesproduksi',
            name='ruangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produksi_monitoring.ruangan'),
        ),
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang diproses', 'Sedang Diproses'), ('Menunggu Verifikasi Admin', 'Menunggu Verifikasi Admin'), ('Siap Dipindahkan', 'Siap Dipindahkan'), ('Selesai Produksi', 'Selesai Produksi')], default='Menunggu', max_length=30),
        ),
    ]
