# Generated by Django 4.2.15 on 2025-04-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0043_alter_prosesproduksi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatproduksi',
            name='hasil_akhir',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
