# Generated by Django 4.2.15 on 2025-06-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0044_riwayatproduksi_hasil_akhir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prosesproduksi',
            options={'verbose_name': 'Proses Produksi', 'verbose_name_plural': 'Proses Produksi'},
        ),
    ]
