# Generated by Django 4.2.15 on 2025-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0045_alter_prosesproduksi_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
