# Generated by Django 4.2.15 on 2025-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0046_ruangan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangan',
            name='slug',
            field=models.SlugField(blank=True, default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
