# Generated by Django 4.2.18 on 2025-08-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0048_idempotencykey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prosesproduksi',
            options={'ordering': ('-waktu_dibuat',), 'verbose_name': 'Proses Produksi', 'verbose_name_plural': 'Proses Produksi'},
        ),
        migrations.AlterField(
            model_name='prosesproduksi',
            name='nomor_batch',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prosesproduksi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu Proses'), ('Sedang diproses', 'Sedang Diproses'), ('Menunggu Verifikasi Admin', 'Menunggu Verifikasi Admin'), ('Siap Dipindahkan', 'Siap Dipindahkan'), ('Selesai Produksi', 'Selesai Produksi')], db_index=True, default='Menunggu', max_length=30),
        ),
    ]
