# Generated by Django 4.2.18 on 2025-08-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi_monitoring', '0049_alter_prosesproduksi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosesproduksi',
            name='nomor_batch',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
